//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int OperationID { get; set; }
        public int WagonID { get; set; }
        public int TypeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TransmitterContractorID { get; set; }
        public Nullable<int> TransmitterDepartmentID { get; set; }
        public int ReceiverContractorID { get; set; }
        public Nullable<int> ReceiverDepartmentID { get; set; }
        public string ContractNumber { get; set; }
        public System.DateTime ContractDate { get; set; }
        public int RentLevel { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual Contractor Contractor1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual OperationType OperationType { get; set; }
        public virtual Wagon Wagon { get; set; }
    }
}
